# Generated by Django 2.2 on 2020-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=512)),
                ('address_status', models.PositiveIntegerField(choices=[(0, '普通'), (1, '默认')], default=0)),
            ],
            options={
                'db_table': 'Sc_address',
                'ordering': ('-address_status',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='商品名')),
                ('img', models.ImageField(upload_to='goods', verbose_name='商品图')),
                ('old_price', models.FloatField(verbose_name='原价')),
                ('sale_price', models.FloatField(verbose_name='拼团价')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
                'db_table': 'Sc_goods',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.PositiveIntegerField()),
                ('initiator_id', models.PositiveIntegerField()),
                ('participant_id', models.PositiveIntegerField(null=True)),
                ('groups_status', models.PositiveIntegerField(choices=[(0, '在团'), (1, '成功')], default=0)),
            ],
            options={
                'db_table': 'Sc_groups',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Sc_imgs',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_id', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('u_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('goods_id', models.PositiveIntegerField()),
                ('goods_name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('goods_img', models.CharField(max_length=256)),
                ('goods_price', models.FloatField()),
                ('goods_num', models.PositiveIntegerField()),
                ('total_price', models.FloatField(verbose_name='商品价格')),
                ('order_status', models.PositiveIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '已送达')], default=0, verbose_name='订单状态')),
                ('address_name', models.CharField(max_length=128)),
                ('address_phone', models.CharField(max_length=11)),
                ('address_address', models.CharField(max_length=512)),
                ('address_note', models.CharField(max_length=512, null=True)),
                ('tracking_number', models.CharField(max_length=128, null=True, verbose_name='快递单号')),
                ('pay_img', models.CharField(max_length=128, null=True, verbose_name='支付凭证')),
                ('t_create', models.DateTimeField(auto_now_add=True, verbose_name='开团时间')),
                ('t_pay', models.DateTimeField(null=True)),
                ('t_send', models.DateTimeField(null=True)),
                ('t_delivery', models.DateTimeField(null=True, verbose_name='送达时间')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
                'db_table': 'Sc_orders',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pay', verbose_name='支付二维码')),
            ],
            options={
                'verbose_name': '支付管理',
                'verbose_name_plural': '支付管理',
                'db_table': 'Sc_pay',
            },
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('sms_code', models.CharField(max_length=64)),
                ('t_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Sc_phone_code',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('phone', models.CharField(max_length=16, unique=True, verbose_name='手机号')),
                ('group_permissions', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='开团权限')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'Sc_users',
            },
        ),
    ]
